version: '3'

services:
  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=djangolinkshortner
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - db
      # - redis
    volumes:
      - .:/app
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=djangolinkshortner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    ports:
      - "543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  # redis:
  #   image: redis:6
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - backend

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: